apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
spec:
  version: 7.15.2
  count: 1
  config:
    elasticsearch.hosts:
      - http://elk-es-http:9200
    elasticsearch.username: elastic
  # secureSettings:
  #   - secretName: kibana-elasticsearch-credentials
  http:
    tls:
      selfSignedCertificate:
        disabled: true

# ---
# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: sidecar-ingress-3
#   namespace: default
#   annotations:
#     kubernetes.io/ingress.class: alb
#     alb.ingress.kubernetes.io/group.name: sidecar-ingress
#     alb.ingress.kubernetes.io/scheme: internet-facing
#     alb.ingress.kubernetes.io/target-type: ip
#     alb.ingress.kubernetes.io/group.order: '2'
#     alb.ingress.kubernetes.io/healthcheck-path: /api/status
# spec:
#   rules:
#     - http:
#         paths:
#           - path: /kibana*
#             backend:
#               serviceName: kibana-kb-http
#               servicePort: 5601
