apiVersion: apps/v1
kind: Deployment
metadata:
  name: transform
  namespace: default
spec:
  replicas: 2

  selector:
    matchLabels:
      name: transform
  template:
    metadata:
      labels:
        name: transform
    spec:
      serviceAccountName: docker-sa
      containers:
        - name: transform
          image: zhaoyi0113/es-kinesis-firehose-transform-go
          resources:
            requests:
              cpu: 1
              memory: 1Gi
            limits:
              cpu: 1
              memory: 1Gi
          ports:
            - containerPort: 8080
          env:
            - name: ES_HOST
              value: "http://elk-es-http:9200"
            - name: INDEX_RETENTION_POLICY
              value: "metrics-log-retention"

---
apiVersion: v1
kind: Service
metadata:
  name: transform
spec:
  selector:
    name: transform
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: NodePort

---
# apiVersion: autoscaling/v2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: transform
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: transform
#   minReplicas: 1
#   maxReplicas: 1
#   metrics:
#   - type: Resource
#     resource:
#       name: cpu
#       target:
#         type: Utilization
#         averageUtilization: 75
#   - type: Resource
#     resource:
#       name: memory
#       target:
#         type: Utilization
#         averageUtilization: 75
